name: Password Sharing Workflow

on: [push]

jobs:
  set_password:
    runs-on: ubuntu-latest
    steps:
      - name: Set Password
        run: echo "PASSWORD=your_password" >> $GITHUB_ENV
      - name: Export vars
        run: echo "PASSWORD=$PASSWORD" >> .env
      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-artifact
          path: .env

  use_password:
    runs-on: ubuntu-latest
    needs: set_password
    permissions:
      contents: read
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: password-artifact
      - name: Read Password
        run: |
          
          source password-artifact/.env
          echo "Password is: $PASSWORD"
